environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "5"
    - nodejs_version: "6"
    - nodejs_version: "7"
    - nodejs_version: "8"

version: 1.0.{build}
image: Visual Studio 2017
clone_folder: c:\projects\node_modules\msnodesqlv8
services: mssql2017

build_script:
- cmd: tool\build.bat
test_script:
- cmd: >-
    netstat -a | findstr 1433

    sqlcmd.exe -S "(local)" -U "sa" -P "Password12!" -Q "select getdate()"

    del binding.gyp

    npm install

    node runtest -a -t tvp -t warnings.js -t compoundqueries.js -t querycancel.js -t txn.js -t datatypes.js -t params.js -t query.js -t querytimeout.js -t connect.js -t bulk.js -t sproc.js -t prepared.js -t userbind.js -t dates.js 2>&1